import type { Question } from './types';

// Fallback questions used when API is unavailable
export const QUESTIONS: Record<string, Question[]> = {
  easy: [
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'What is the capital city of France?',ar:'ما هي عاصمة فرنسا؟'}, opts:{en:['Lyon','Paris','Marseille','Nice'],ar:['ليون','باريس','مارسيليا','نيس']}, ans:1 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'How many legs does a spider have?',ar:'كم عدد أرجل العنكبوت؟'}, opts:{en:['4','6','8','10'],ar:['٤','٦','٨','١٠']}, ans:2 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'What colour is the sky on a clear day?',ar:'ما لون السماء في يوم صافٍ؟'}, opts:{en:['Green','Yellow','Blue','Purple'],ar:['أخضر','أصفر','أزرق','بنفسجي']}, ans:2 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'What is the main ingredient in chocolate?',ar:'ما المكوّن الرئيسي في الشوكولاتة؟'}, opts:{en:['Vanilla','Cocoa','Coffee','Caramel'],ar:['فانيليا','كاكاو','قهوة','كراميل']}, ans:1 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'Who was the first person to walk on the Moon?',ar:'من كان أوّل إنسان يمشي على سطح القمر؟'}, opts:{en:['Buzz Aldrin','Yuri Gagarin','Neil Armstrong','John Glenn'],ar:['باز ألدرين','يوري غاغارين','نيل أرمسترونغ','جون غلين']}, ans:2 },
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'What is the largest ocean on Earth?',ar:'ما أكبر محيط على وجه الأرض؟'}, opts:{en:['Atlantic','Indian','Arctic','Pacific'],ar:['الأطلسي','الهندي','المتجمد الشمالي','الهادئ']}, ans:3 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'How many bones does an adult shark have?',ar:'كم عدد عظام سمكة القرش البالغة؟'}, opts:{en:['Zero','22','64','120'],ar:['صفر','٢٢','٦٤','١٢٠']}, ans:0 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'How many planets are in our Solar System?',ar:'كم عدد الكواكب في مجموعتنا الشمسية؟'}, opts:{en:['7','8','9','10'],ar:['٧','٨','٩','١٠']}, ans:1 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'What fruit is used to make wine?',ar:'ما الفاكهة التي يُصنع منها النبيذ؟'}, opts:{en:['Apple','Orange','Grape','Strawberry'],ar:['تفاح','برتقال','عنب','فراولة']}, ans:2 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'Which country built the Great Wall?',ar:'أيّ دولة بنت سور الصين العظيم؟'}, opts:{en:['Japan','India','China','Korea'],ar:['اليابان','الهند','الصين','كوريا']}, ans:2 },
  ],
  medium: [
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'What is the capital city of Australia?',ar:'ما هي عاصمة أستراليا؟'}, opts:{en:['Sydney','Melbourne','Canberra','Brisbane'],ar:['سيدني','ملبورن','كانبرا','بريزبين']}, ans:2 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'In which year did World War II end?',ar:'في أيّ عام انتهت الحرب العالمية الثانية؟'}, opts:{en:['1943','1944','1945','1946'],ar:['١٩٤٣','١٩٤٤','١٩٤٥','١٩٤٦']}, ans:2 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'What is the chemical symbol for gold?',ar:'ما هو الرمز الكيميائي للذهب؟'}, opts:{en:['Go','Gd','Au','Ag'],ar:['Go','Gd','Au','Ag']}, ans:2 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'Which country is the birthplace of sushi?',ar:'أيّ بلد يُعدّ مهد السوشي؟'}, opts:{en:['China','Korea','Thailand','Japan'],ar:['الصين','كوريا','تايلاند','اليابان']}, ans:3 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'What is the fastest land animal on Earth?',ar:'ما أسرع حيوان بري على الأرض؟'}, opts:{en:['Lion','Cheetah','Greyhound','Pronghorn'],ar:['أسد','فهد','كلب الصيد','الظبي']}, ans:1 },
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'Which is the longest river in the world?',ar:'ما أطول نهر في العالم؟'}, opts:{en:['Amazon','Nile','Mississippi','Yangtze'],ar:['الأمازون','النيل','المسيسيبي','اليانغتسي']}, ans:1 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'Who was the first woman to win a Nobel Prize?',ar:'من كانت أوّل امرأة تفوز بجائزة نوبل؟'}, opts:{en:['Rosalind Franklin','Ada Lovelace','Marie Curie','Florence Nightingale'],ar:['روزاليند فرانكلين','آدا لوفلاس','ماري كوري','فلورنس نايتنغيل']}, ans:2 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'How many bones are in the adult human body?',ar:'كم عدد عظام جسم الإنسان البالغ؟'}, opts:{en:['196','206','216','226'],ar:['١٩٦','٢٠٦','٢١٦','٢٢٦']}, ans:1 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'What is the primary ingredient in guacamole?',ar:'ما المكوّن الرئيسي في الغواكامولي؟'}, opts:{en:['Tomato','Lime','Avocado','Onion'],ar:['طماطم','ليمون','أفوكادو','بصل']}, ans:2 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'How many hearts does an octopus have?',ar:'كم قلبًا يمتلك الأخطبوط؟'}, opts:{en:['One','Two','Three','Four'],ar:['واحد','اثنان','ثلاثة','أربعة']}, ans:2 },
  ],
  hard: [
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'Which country has the most natural lakes?',ar:'أيّ دولة تمتلك أكبر عدد من البحيرات الطبيعية؟'}, opts:{en:['USA','Russia','Canada','Finland'],ar:['الولايات المتحدة','روسيا','كندا','فنلندا']}, ans:2 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'In what year was the Magna Carta signed?',ar:'في أيّ عام وُقِّعت الماغنا كارتا؟'}, opts:{en:['1215','1315','1115','1415'],ar:['١٢١٥','١٣١٥','١١١٥','١٤١٥']}, ans:0 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'Approximately how fast does light travel (km/s)?',ar:'ما تقريبًا سرعة الضوء (كم/ث)؟'}, opts:{en:['200,000','300,000','400,000','500,000'],ar:['٢٠٠٬٠٠٠','٣٠٠٬٠٠٠','٤٠٠٬٠٠٠','٥٠٠٬٠٠٠']}, ans:1 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'What Japanese drink is made from fermented rice?',ar:'ما المشروب الياباني المصنوع من الأرز المخمّر؟'}, opts:{en:['Soju','Baijiu','Sake','Shochu'],ar:['سوجو','باييجيو','ساكي','شوتشو']}, ans:2 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'What is the collective noun for a group of flamingos?',ar:'ما الاسم الجماعي لمجموعة من طيور الفلامنغو؟'}, opts:{en:['Flock','Flamboyance','Colony','Gaggle'],ar:['سرب','لهب','مستعمرة','قطيع']}, ans:1 },
    { cat:{en:'Geography',ar:'جغرافيا'}, q:{en:'Which river flows through Baghdad?',ar:'أيّ نهر يمرّ ببغداد؟'}, opts:{en:['Euphrates','Tigris','Nile','Indus'],ar:['الفرات','دجلة','النيل','الإندوس']}, ans:1 },
    { cat:{en:'History',ar:'تاريخ'}, q:{en:'Who painted the ceiling of the Sistine Chapel?',ar:'من رسم سقف كنيسة سيستين؟'}, opts:{en:['Leonardo da Vinci','Raphael','Donatello','Michelangelo'],ar:['ليوناردو دافينشي','رافائيل','دوناتيلو','مايكل أنجلو']}, ans:3 },
    { cat:{en:'Science',ar:'علوم'}, q:{en:'Most abundant gas in Earth\'s atmosphere?',ar:'أكثر الغازات وفرةً في الغلاف الجوي؟'}, opts:{en:['Oxygen','Carbon Dioxide','Nitrogen','Argon'],ar:['الأكسجين','ثاني أكسيد الكربون','النيتروجين','الأرغون']}, ans:2 },
    { cat:{en:'Food & Drink',ar:'طعام وشراب'}, q:{en:'Which nut is used to make marzipan?',ar:'أيّ مكسّر يُستخدم في صنع المرزبان؟'}, opts:{en:['Walnut','Cashew','Pistachio','Almond'],ar:['جوز','كاجو','فستق','لوز']}, ans:3 },
    { cat:{en:'Animals',ar:'حيوانات'}, q:{en:'What is the gestation period of an elephant?',ar:'ما مدة حمل الفيلة؟'}, opts:{en:['12 months','18 months','22 months','28 months'],ar:['١٢ شهرًا','١٨ شهرًا','٢٢ شهرًا','٢٨ شهرًا']}, ans:2 },
  ],
};

export const STRINGS: Record<string, Record<string, string>> = {
  en: {
    app_title:'Family Trivia', app_sub:'A Game For Everyone',
    btn_login:'Login with Mobile', btn_guest:'Play as Guest',
    or:'or',
    guest_note:'Guests can play but cannot save scores or create custom games. Login to unlock all features.',
    login_title:'Welcome Back', login_sub:'Enter your details to continue',
    label_mobile:'Mobile Number', ph_mobile:'e.g. 0501234567',
    label_name:'Your Name', ph_name:'e.g. Sarah',
    btn_login_go:'Continue', btn_back:'← Back',
    err_mobile:'Please enter a valid mobile number (at least 7 digits)',
    err_name:'Please enter your name (at least 2 characters)',
    home_guest:'Playing as Guest',
    home_welcome:'Hello,',
    btn_logout:'Sign Out',
    lbl_mode:'Game Mode',
    mode_ready:'Question Bank', mode_ready_desc:'Questions from the web',
    mode_custom:'Custom Game', mode_custom_desc:'Your own categories',
    // Step labels
    step_teams:'Set Up Teams',
    step_teams_sub:'Who is playing today?',
    step_difficulty:'Choose Difficulty',
    step_difficulty_sub:'How tough should the questions be?',
    step_categories:'Pick Your Topics',
    step_categories_sub:'Choose one or more — or leave all selected',
    lbl_next:'Next  →',
    lbl_start:'▶  Start Game',
    cats_loading:'Loading topics…',
    cat_select_all:'Select All',
    cat_clear:'Clear',
    cats_none_hint:'No topics selected — all topics will be used',
    // Difficulty descriptions
    diff_easy:'Easy', diff_medium:'Medium', diff_hard:'Hard',
    diff_easy_desc:'Great for all ages', diff_medium_desc:'A good challenge', diff_hard_desc:'For trivia masters',
    lbl_teams:'Teams',
    label_t1:'Team 1 Name', ph_t1:'e.g. The Brains',
    label_t2:'Team 2 Name', ph_t2:'e.g. Quiz Kings',
    btn_start:'▶  Start Game',
    btn_build:'Build Custom Game',
    btn_lb:'Leaderboard',
    guest_promo:'Login to save scores & build custom games →',
    btn_login_now:'Login',
    lb_title:'🏆 Leaderboard',
    btn_clear:'Clear All Records',
    lb_col_date:'Date', lb_col_player:'Player',
    lb_col_scores:'Scores', lb_col_diff:'Difficulty', lb_col_mode:'Mode',
    lb_empty:'No games recorded yet.\nPlay while logged in to see scores here.',
    stat_games:'Games Played', stat_best:'Best Score', stat_avg:'Avg Score',
    mode_ready_lb:'Bank', mode_custom_lb:'Custom',
    builder_title:'Custom Game Builder',
    builder_sub:'Create categories — each needs 6 questions to play',
    btn_add_category:'+ Add Category',
    lbl_cat_name:'Category Name',
    lbl_cat_image:'Image URL (optional)',
    ph_cat_name:'e.g. Sports, Movies, Science…',
    ph_cat_image:'https://example.com/image.jpg',
    btn_add_cat_submit:'Add Category',
    err_cat_name:'Please enter a category name',
    addcat_title:'New Category',
    builder_no_cats:'No categories yet.\nTap \'+ Add Category\' to get started.',
    builder_play_note:'Complete at least 1 category (6 questions) to play',
    btn_add_q:'+ Add Question',
    btn_play_custom:'▶  Play Custom Game',
    q_count:'questions',
    addq_for_cat:'Adding question for:',
    btn_quit:'✕ Quit',
    score_lbl:'Score',
    lbl_steal:'STEAL!',
    q_of:'of',
    results_title:'Final Results',
    winner_wins:'🏆 Wins!',
    draw_msg:'🤝 It\'s a Draw!',
    btn_again:'Play Again',
    btn_home:'Return to Home',
    quit_title:'Quit Game?',
    quit_msg:'Are you sure? Your current game progress will be lost.',
    quit_confirm:'Quit to Home',
    btn_cancel:'Cancel',
    clear_title:'Clear Leaderboard?',
    clear_msg:'This will permanently delete all game records. This cannot be undone.',
    clear_confirm:'Clear All',
    addq_title:'Add Question',
    lbl_q_text:'Question', ph_q_text:'Type your question here…',
    lbl_q_cat:'Category',
    lbl_q_opts:'Options (A–D)',
    lbl_q_correct:'Correct Answer',
    btn_add_q_submit:'Add Question',
    err_q_text:'Please enter a question',
    err_q_opts:'Please fill in all 4 options',
    err_q_correct:'Please select the correct answer',
    cat_geo:'Geography', cat_hist:'History', cat_sci:'Science',
    cat_food:'Food & Drink', cat_ani:'Animals', cat_gen:'General',
    fb_correct:'✔ Correct! +1 point for',
    fb_wrong:'✘ Wrong! The answer was',
    fb_timeout_steal:'gets 5 seconds to steal!',
    fb_steal_fail:'No steal! The answer was',
    diff_easy_lb:'Easy', diff_medium_lb:'Medium', diff_hard_lb:'Hard',
    custom_lb:'Custom',
    lbl_loading:'Loading questions…',
    err_api:'Could not load questions from web. Using built-in set instead.',
    btn_retry:'Try Again',
  },
  ar: {
    app_title:'مسابقة عائلية', app_sub:'لعبة للجميع',
    btn_login:'الدخول برقم الجوال', btn_guest:'العب كضيف',
    or:'أو',
    guest_note:'الضيوف يمكنهم اللعب لكن لا يمكنهم حفظ النتائج أو إنشاء ألعاب مخصصة. سجّل دخولك لفتح جميع المميزات.',
    login_title:'مرحباً بعودتك', login_sub:'أدخل بياناتك للمتابعة',
    label_mobile:'رقم الجوال', ph_mobile:'مثال: 0501234567',
    label_name:'اسمك', ph_name:'مثال: سارة',
    btn_login_go:'متابعة', btn_back:'→ رجوع',
    err_mobile:'الرجاء إدخال رقم جوال صحيح (٧ أرقام على الأقل)',
    err_name:'الرجاء إدخال اسمك (٢ حرف على الأقل)',
    home_guest:'تلعب كضيف',
    home_welcome:'أهلاً،',
    btn_logout:'تسجيل الخروج',
    lbl_mode:'نمط اللعبة',
    mode_ready:'بنك الأسئلة', mode_ready_desc:'أسئلة من الإنترنت',
    mode_custom:'لعبة مخصصة', mode_custom_desc:'فئاتك الخاصة',
    step_teams:'إعداد الفرق',
    step_teams_sub:'من يلعب اليوم؟',
    step_difficulty:'اختر الصعوبة',
    step_difficulty_sub:'كم تريد الأسئلة أن تكون صعبة؟',
    step_categories:'اختر المواضيع',
    step_categories_sub:'اختر واحداً أو أكثر — أو اتركها جميعاً محددة',
    lbl_next:'التالي  →',
    lbl_start:'▶ ابدأ اللعبة',
    cats_loading:'جارٍ تحميل المواضيع…',
    cat_select_all:'اختر الكل',
    cat_clear:'مسح',
    cats_none_hint:'لا مواضيع محددة — ستُستخدم جميع المواضيع',
    diff_easy:'سهل', diff_medium:'متوسط', diff_hard:'صعب',
    diff_easy_desc:'مناسب لجميع الأعمار', diff_medium_desc:'تحدٍّ جيد', diff_hard_desc:'لمحترفي الأسئلة',
    lbl_teams:'الفرق',
    label_t1:'اسم الفريق الأول', ph_t1:'مثال: العقول',
    label_t2:'اسم الفريق الثاني', ph_t2:'مثال: ملوك الأسئلة',
    btn_start:'▶ ابدأ اللعبة',
    btn_build:'بناء لعبة مخصصة',
    btn_lb:'لوحة المتصدرين',
    guest_promo:'← سجّل دخولك لحفظ النتائج وبناء الألعاب',
    btn_login_now:'دخول',
    lb_title:'🏆 لوحة المتصدرين',
    btn_clear:'مسح جميع السجلات',
    lb_col_date:'التاريخ', lb_col_player:'اللاعب',
    lb_col_scores:'النتائج', lb_col_diff:'الصعوبة', lb_col_mode:'النمط',
    lb_empty:'لا توجد ألعاب بعد.\nالعب وأنت مسجّل لتظهر نتائجك هنا.',
    stat_games:'الألعاب', stat_best:'أفضل نتيجة', stat_avg:'متوسط النتيجة',
    mode_ready_lb:'بنك', mode_custom_lb:'مخصصة',
    builder_title:'بناء لعبة مخصصة',
    builder_sub:'أنشئ فئات — تحتاج كل فئة ٦ أسئلة للعب',
    btn_add_category:'+ إضافة فئة',
    lbl_cat_name:'اسم الفئة',
    lbl_cat_image:'رابط الصورة (اختياري)',
    ph_cat_name:'مثال: رياضة، أفلام، علوم…',
    ph_cat_image:'https://example.com/image.jpg',
    btn_add_cat_submit:'إضافة الفئة',
    err_cat_name:'الرجاء إدخال اسم الفئة',
    addcat_title:'فئة جديدة',
    builder_no_cats:'لا توجد فئات بعد.\nاضغط \'+ إضافة فئة\' للبدء.',
    builder_play_note:'أكمل فئة واحدة على الأقل (٦ أسئلة) للعب',
    btn_add_q:'+ إضافة سؤال',
    btn_play_custom:'▶ العب اللعبة المخصصة',
    q_count:'أسئلة',
    addq_for_cat:'إضافة سؤال لـ:',
    btn_quit:'إنهاء ✕',
    score_lbl:'النقاط',
    lbl_steal:'سرقة!',
    q_of:'من',
    results_title:'النتائج النهائية',
    winner_wins:'🏆 يفوز!',
    draw_msg:'🤝 تعادل!',
    btn_again:'العب مجدداً',
    btn_home:'العودة للرئيسية',
    quit_title:'إنهاء اللعبة؟',
    quit_msg:'هل أنت متأكد؟ ستفقد تقدمك الحالي في اللعبة.',
    quit_confirm:'العودة للرئيسية',
    btn_cancel:'إلغاء',
    clear_title:'مسح لوحة المتصدرين؟',
    clear_msg:'سيتم حذف جميع سجلات الألعاب بشكل نهائي.',
    clear_confirm:'مسح الكل',
    addq_title:'إضافة سؤال',
    lbl_q_text:'السؤال', ph_q_text:'اكتب سؤالك هنا…',
    lbl_q_cat:'الفئة',
    lbl_q_opts:'الخيارات (أ–د)',
    lbl_q_correct:'الإجابة الصحيحة',
    btn_add_q_submit:'إضافة السؤال',
    err_q_text:'الرجاء إدخال السؤال',
    err_q_opts:'الرجاء ملء جميع الخيارات الأربعة',
    err_q_correct:'الرجاء تحديد الإجابة الصحيحة',
    cat_geo:'جغرافيا', cat_hist:'تاريخ', cat_sci:'علوم',
    cat_food:'طعام وشراب', cat_ani:'حيوانات', cat_gen:'عام',
    fb_correct:'✔ صحيح! نقطة لـ',
    fb_wrong:'✘ خطأ! الإجابة كانت',
    fb_timeout_steal:'لديه ٥ ثوانٍ للسرقة!',
    fb_steal_fail:'فاتت الفرصة! الإجابة كانت',
    diff_easy_lb:'سهل', diff_medium_lb:'متوسط', diff_hard_lb:'صعب',
    custom_lb:'مخصصة',
    lbl_loading:'جارٍ تحميل الأسئلة…',
    err_api:'تعذّر تحميل أسئلة الإنترنت. تم استخدام الأسئلة الاحتياطية.',
    btn_retry:'إعادة المحاولة',
  },
};

export const LABELS = ['A', 'B', 'C', 'D'] as const;
